name: delivery_tracking_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Layout
  dotted_border: ^2.0.0+3

  # Network
  http: ^1.2.0
  cached_network_image: ^3.3.0
  web_socket_channel: ^2.4.0
  mime: ^1.0.4

  # Image & Camera
  image_picker: ^1.1.2

  # Location
  geolocator: ^14.0.2
  geocoding: ^2.2.1
  latlong2: ^0.9.1

  # Map
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.0.0

  # Utility
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ต้องมี dependency_overrides เพื่อบังคับเวอร์ชันที่เข้ากันได้
dependency_overrides:
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

flutter:
  uses-material-design: true

  # Assets: ต้องเยื้องให้ถูกต้อง
  assets:
    - lib/assets/
